# Generated by Django 4.2.7 on 2025-02-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='rental_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], default='daily', max_length=10),
        ),
    ]
