# Generated by Django 4.2.7 on 2025-02-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_duration_cartitem_rental_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='rental_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily')], default='Hourly', max_length=10),
        ),
    ]
