# Generated by Django 4.2.7 on 2025-02-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_rental_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='rental_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily')], default='hourly', max_length=10),
        ),
    ]
